import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

import './globals.css'
import ReduxProvider from "./components/reduxprovider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
        <body className={`antialiased`}>
        <ReduxProvider>
        <Navbar/>
        {children}
        <Footer/>
        </ReduxProvider>
       </body>
      </html>
    
  );
  
}
